server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: base-gateway
  cloud:
    gateway:
      routes:
      - id: breed
        uri: http://localhost:9999
        predicates:
        - Path=/login/*
    config:
      name: bootstrap-dev
      profile: dev
      label: master
      uri: http://localhost:8888